trailing_comma:
  mandatory_comma: true

disabled_rules:
  - force_cast

opt_in_rules:
  - closure_spacing
  - collection_alignment
  - convenience_type
  - empty_collection_literal
  - empty_count
  - empty_string
  - explicit_init
  - identical_operands
  - legacy_multiple
  - literal_expression_end_indentation
  - modifier_order
  - overridden_super_call
  - prefer_self_in_static_references
  - prefer_zero_over_explicit_init
  - private_action
  - prohibited_super_call
  - quick_discouraged_focused_test
  - shorthand_optional_binding
  - sorted_imports
  - vertical_parameter_alignment_on_call
  - weak_delegate
  - yoda_condition
